import { 
    LayoutDashboard, 
    Server, 
    Settings, 
    Sparkles, 
    Monitor, 
    MapPin, 
    Cpu, 
    Network, 
    DollarSign, 
    Shield, 
    Bot, 
    Wallet, 
    Scan, 
    GitBranch, 
    Ticket, 
    BarChart2, 
    Trophy, 
    Zap, 
    Clock, 
    LifeBuoy, 
    RotateCcw, 
    ShoppingBag, 
    Trash2,
    HeartHandshake,
    LayoutGrid
} from 'lucide-react';

export const ALL_NAV_ITEMS = [
    { label: 'Dashboard', href: '/', icon: LayoutDashboard },
    { label: 'Support & Tickets', href: '/tickets', icon: LifeBuoy },
    { label: 'Unit Command Hub', href: '/unit-command', icon: HeartHandshake },
    { label: 'Support Queue', href: '/support-dashboard', icon: LayoutGrid },
    { label: 'Enterprise', href: '/enterprise', icon: Sparkles },
    { label: 'Topology', href: '/network-topology', icon: Network },
    { label: 'Assets', href: '/assets', icon: Server },
    { label: 'Software', href: '/software', icon: Monitor },
    { label: 'Patch Management', href: '/patch-management', icon: Shield },
    { label: 'RFID Management', href: '/rfid', icon: Cpu },
    { label: 'Barcode Scan', href: '/barcode-scan', icon: Scan },
    { label: 'Workflows', href: '/workflows', icon: GitBranch },
    { label: 'Ticket Automation', href: '/tickets/automation', icon: Zap },
    { label: 'SLA Center', href: '/tickets/sla', icon: Clock },
    { label: 'Analytics', href: '/analytics', icon: BarChart2 },
    { label: 'Top Performers', href: '/performers', icon: Trophy },
    { label: 'Gate Pass', href: '/gate-pass', icon: Ticket },
    { label: 'Locations', href: '/locations', icon: MapPin },
    { label: 'Agents', href: '/agents', icon: Cpu },
    { label: 'Port Policies', href: '/security/port-policies', icon: Shield },
    { label: 'Renewals', href: '/renewals', icon: RotateCcw },
    { label: 'Logistics Hub', href: '/procurement', icon: ShoppingBag },
    { label: 'Financial Governance', href: '/finance', icon: Wallet },
    { label: 'Budget Queue', href: '/finance/budget-queue', icon: DollarSign },
    { label: 'Disposal', href: '/disposal', icon: Trash2 },
    { label: 'Pricing', href: '/pricing', icon: DollarSign },
    { label: 'Settings', href: '/settings', icon: Settings },
];

export const ROLE_DASHBOARD_MAP = {
    'ADMIN': '/dashboard/system-admin',
    'ASSET_MANAGER': '/dashboard/asset-inventory-manager',
    'PROCUREMENT': '/procurement',
    'IT_MANAGEMENT': '/dashboard/system-admin',
    'CEO': '/dashboard/system-admin',
    'CFO': '/dashboard/system-admin',
    'FINANCE': '/finance',
    'SUPPORT': '/',
    'MANAGER': '/',
    'END_USER': '/'
};
