export const PERSONA_MAP = {
    "ADMIN": [
        { "value": "AC_TECHNICIAN", "label": "AC TECHNICIAN" },
        { "value": "ADMIN_HEAD", "label": "ADMIN HEAD" },
        { "value": "ADMIN_MANAGER", "label": "ADMIN MANAGER" },
        { "value": "DRIVER", "label": "DRIVER" },
        { "value": "ELECTRICIAN", "label": "ELECTRICIAN" },
        { "value": "FACILITY_MANAGER", "label": "FACILITY MANAGER" },
        { "value": "HK", "label": "HK" },
        { "value": "INTERNAL_SECURITY", "label": "INTERNAL SECURITY" },
        { "value": "MIS_EXECUTIVE", "label": "MIS EXECUTIVE" },
        { "value": "OFFICE_BOY", "label": "OFFICE BOY" },
        { "value": "RDC__HUB_MANAGER", "label": "RDC- HUB MANAGER" },
        { "value": "RECEPTIONIST", "label": "RECEPTIONIST" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" }
    ],
    "B&M": [
        { "value": "ASST_DIV_HEAD", "label": "ASST DIV-HEAD" },
        { "value": "ASST_DIV_PD_HEAD", "label": "ASST DIV-PD HEAD" },
        { "value": "BUYER", "label": "BUYER" },
        { "value": "CAD_JR.EXECUTIVE", "label": "CAD-JR.EXECUTIVE" },
        { "value": "CAD_PATTERN_MASTER", "label": "CAD-PATTERN MASTER" },
        { "value": "CAT_PLANNER", "label": "CAT-PLANNER" },
        { "value": "DEPT_HEAD", "label": "DEPT HEAD" },
        { "value": "DIV_HEAD", "label": "DIV-HEAD" },
        { "value": "FAB_DIV_HEAD", "label": "FAB-DIV-HEAD" },
        { "value": "FAB_HEAD", "label": "FAB-HEAD" },
        { "value": "FAB_JR.EXECUTIVE", "label": "FAB-JR.EXECUTIVE" },
        { "value": "HELPER", "label": "HELPER" },
        { "value": "JR_EXECUTIVE", "label": "JR EXECUTIVE" },
        { "value": "JR_DZNR", "label": "JR-DZNR" },
        { "value": "LOCATION_HEAD", "label": "LOCATION HEAD" },
        { "value": "LOCATION_QC_BUYER_EDP", "label": "LOCATION QC/BUYER/EDP" },
        { "value": "MARKET_BUYER", "label": "MARKET BUYER" },
        { "value": "MDM_HEAD", "label": "MDM-HEAD" },
        { "value": "MDM_JR.EXECUTIVE", "label": "MDM-JR.EXECUTIVE" },
        { "value": "MDM_SR.EXECUTIVE", "label": "MDM-SR.EXECUTIVE" },
        { "value": "MERCHANT", "label": "MERCHANT" },
        { "value": "OB_JR.EXECUTIVE", "label": "OB JR.EXECUTIVE" },
        { "value": "OB_HEAD", "label": "OB-HEAD" },
        { "value": "PATTERN_MASTER", "label": "PATTERN MASTER" },
        { "value": "PC_ASST_HEAD", "label": "PC-ASST HEAD" },
        { "value": "PC_HEAD", "label": "PC-HEAD" },
        { "value": "PD_HEAD", "label": "PD-HEAD" },
        { "value": "PO_OFFICER", "label": "PO-OFFICER" },
        { "value": "PRD_HEAD", "label": "PRD-HEAD" },
        { "value": "QC_DIV_HEAD", "label": "QC-DIV HEAD" },
        { "value": "QC_HEAD", "label": "QC-HEAD" },
        { "value": "SAMPLING_HEAD", "label": "SAMPLING HEAD" },
        { "value": "SR_EXECUTIVE", "label": "SR EXECUTIVE" },
        { "value": "SUB_DIV", "label": "SUB-DIV" },
        { "value": "SUB_DIV_PD_DZNR_HEAD", "label": "SUB-DIV PD DZNR HEAD" },
        { "value": "T&A", "label": "T&A" },
        { "value": "TAILOR", "label": "TAILOR" }
    ],
    "BD": [
        { "value": "ASSISTANT_BD_HEAD", "label": "ASSISTANT BD HEAD" },
        { "value": "BD_HEAD", "label": "BD HEAD" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "REGIONAL_MANAGER", "label": "REGIONAL MANAGER" }
    ],
    "F&A": [
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "CFO", "label": "CFO" },
        { "value": "DGM", "label": "DGM" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "JUNIOR_EXECUTIVE", "label": "JUNIOR EXECUTIVE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" }
    ],
    "HR": [
        { "value": "ASSISTANT_HR_HEAD", "label": "ASSISTANT HR HEAD" },
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "HR_HEAD", "label": "HR HEAD" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" },
        { "value": "TRAINER", "label": "TRAINER" }
    ],
    "INVENTORY": [
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "JUNIOR_EXECUTIVE", "label": "JUNIOR EXECUTIVE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" }
    ],
    "IT": [
        { "value": "ABAP_LEAD", "label": "ABAP-LEAD" },
        { "value": "ABAPER", "label": "ABAPER" },
        { "value": "AI_ENGINEER", "label": "AI ENGINEER" },
        { "value": "ANALYTICS_LEAD", "label": "ANALYTICS LEAD" },
        { "value": "ASSISTANT_HEAD_ERP_APPS_NON_SAP", "label": "ASSISTANT HEAD ERP APPS-NON-SAP" },
        { "value": "AXAPTA_SUPPORT_MANAGER", "label": "AXAPTA-SUPPORT MANAGER" },
        { "value": "BASIS_HEAD", "label": "BASIS HEAD" },
        { "value": "CIO", "label": "CIO" },
        { "value": "DATA_ANALYST", "label": "DATA ANALYST" },
        { "value": "DBA", "label": "DBA" },
        { "value": "DEVELOPER", "label": "DEVELOPER" },
        { "value": "DIGITAL_TRANSFORMATION__HEAD", "label": "DIGITAL TRANSFORMATION -HEAD" },
        { "value": "DT_ASSISTANT", "label": "DT ASSISTANT" },
        { "value": "EA_TO_CIO", "label": "EA TO CIO" },
        { "value": "EA_TO_HEAD_ERP_APPS___SAP", "label": "EA TO HEAD ERP APPS - SAP" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "FICO_FUNCTIONAL", "label": "FICO-FUNCTIONAL" },
        { "value": "HEAD_ERP_APPS___SAP", "label": "HEAD ERP APPS - SAP" },
        { "value": "HEAD_ERP_APPS_NON_SAP", "label": "HEAD ERP APPS-NON-SAP" },
        { "value": "HEAD_IT_PROCUREMENT_&_NEGOTIATIONS", "label": "HEAD IT PROCUREMENT & NEGOTIATIONS" },
        { "value": "HEAD_IT_SECURITY_&_COMPLIANCE", "label": "HEAD IT SECURITY & COMPLIANCE" },
        { "value": "HEAD_PMO", "label": "HEAD PMO" },
        { "value": "HEAD_IT_SUPPORT", "label": "HEAD-IT SUPPORT" },
        { "value": "INFRA_HEAD", "label": "INFRA HEAD" },
        { "value": "JUNIOR_EXECUTIVE", "label": "JUNIOR EXECUTIVE" },
        { "value": "MANAGEMENT_TRAINEE", "label": "MANAGEMENT TRAINEE" },
        { "value": "MM_FUNCTIONAL", "label": "MM-FUNCTIONAL" },
        { "value": "NSO_IT_SUPPORT_EXECUTIVE", "label": "NSO-IT SUPPORT EXECUTIVE" },
        { "value": "PM_NON_SAP", "label": "PM-NON SAP" },
        { "value": "PM_SAP", "label": "PM-SAP" },
        { "value": "PMO_MT", "label": "PMO-MT" },
        { "value": "PROCUREMENT_ASSISTANT", "label": "PROCUREMENT ASSISTANT" },
        { "value": "PS_FUNCTIONAL", "label": "PS-FUNCTIONAL" },
        { "value": "SECURITY_ENGINEER", "label": "SECURITY ENGINEER" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" },
        { "value": "WM_FUNCTIONAL", "label": "WM-FUNCTIONAL" }
    ],
    "LEGAL & COMPANY SECRETARY": [
        { "value": "ASST._CS", "label": "ASST. CS" },
        { "value": "ASST._MANAGER", "label": "ASST. MANAGER" },
        { "value": "HEAD_CS", "label": "HEAD CS" }
    ],
    "LOSS PREVENTION": [
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "CCTV_HEAD", "label": "CCTV HEAD" },
        { "value": "CCTV_TECHNICIAN", "label": "CCTV TECHNICIAN" },
        { "value": "CLUSTER_LP", "label": "CLUSTER-LP" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "MIS_EXECUTIVE", "label": "MIS EXECUTIVE" },
        { "value": "REGIONAL_LP", "label": "REGIONAL-LP" },
        { "value": "ZONAL_LP", "label": "ZONAL-LP" }
    ],
    "MARKETING": [
        { "value": "CUSTOMER_CARE_EXECUTIVE", "label": "CUSTOMER CARE EXECUTIVE" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "GRAPHIC_DESIGNER", "label": "GRAPHIC DESIGNER" },
        { "value": "JUNIOR_EXECUTIVE", "label": "JUNIOR EXECUTIVE" },
        { "value": "MANAGEMENT_TRAINEE", "label": "MANAGEMENT TRAINEE" },
        { "value": "NSO_VERTICAL_HEAD", "label": "NSO VERTICAL HEAD" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" }
    ],
    "NSO": [
        { "value": "ASSISTANT_NSO_HEAD", "label": "ASSISTANT NSO HEAD" },
        { "value": "CLUSTER_MANAGER", "label": "CLUSTER MANAGER" },
        { "value": "CLUSTER_LP", "label": "CLUSTER-LP" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "HR_MANAGER", "label": "HR MANAGER" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "NSO_AUDIT_HEAD", "label": "NSO AUDIT HEAD" },
        { "value": "NSO_FINANCE_HEAD", "label": "NSO FINANCE HEAD" },
        { "value": "NSO_HEAD", "label": "NSO HEAD" },
        { "value": "NSO_HR_HEAD", "label": "NSO HR HEAD" },
        { "value": "NSO_MARKETING_HEAD", "label": "NSO MARKETING HEAD" },
        { "value": "NSO_PLANNING_HEAD", "label": "NSO PLANNING HEAD" },
        { "value": "NSO_SCM_HEAD", "label": "NSO SCM HEAD" },
        { "value": "NSO_SUPPORT_HEAD", "label": "NSO SUPPORT HEAD" },
        { "value": "REGIONAL_MANAGER", "label": "REGIONAL MANAGER" }
    ],
    "PLANNING": [
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" }
    ],
    "PROJECT": [
        { "value": "ASSISTANT_MANAGER", "label": "ASSISTANT MANAGER" },
        { "value": "ASSISTANT_PROJECT_HEAD", "label": "ASSISTANT PROJECT HEAD" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "MIS_EXECUTIVE", "label": "MIS EXECUTIVE" },
        { "value": "PROJECT_HEAD", "label": "PROJECT HEAD" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" },
        { "value": "SENIOR_MANAGER", "label": "SENIOR MANAGER" },
        { "value": "SUPERVISOR", "label": "SUPERVISOR" }
    ],
    "RETAIL": [
        { "value": "ASSISTANT_RETAIL_PLANNING_HEAD", "label": "ASSISTANT RETAIL PLANNING HEAD" },
        { "value": "ASSISTANT_TO_RETAIL_HEAD", "label": "ASSISTANT TO RETAIL HEAD" },
        { "value": "ASSISTANT_TO_ZONAL_SUPPORT_HEAD", "label": "ASSISTANT TO ZONAL SUPPORT HEAD" },
        { "value": "ASSISTANT_ZONAL_MANAGER", "label": "ASSISTANT ZONAL MANAGER" },
        { "value": "CLUSTER_MANAGER", "label": "CLUSTER MANAGER" },
        { "value": "CLUSTER_PLANNER", "label": "CLUSTER PLANNER" },
        { "value": "MIS_EXECUTIVE", "label": "MIS EXECUTIVE" },
        { "value": "REGIONAL_MANAGER", "label": "REGIONAL MANAGER" },
        { "value": "REGIONAL_PLANNER", "label": "REGIONAL PLANNER" },
        { "value": "RETAIL_HEAD", "label": "RETAIL HEAD" },
        { "value": "RETAIL_PLANNING_HEAD", "label": "RETAIL PLANNING HEAD" },
        { "value": "ZONAL_MANAGER", "label": "ZONAL MANAGER" },
        { "value": "ZONAL_PLANNER", "label": "ZONAL PLANNER" },
        { "value": "ZONAL_SUPPORT_HEAD", "label": "ZONAL SUPPORT HEAD" }
    ],
    "RETAIL OPERATION": [
        { "value": "ASM", "label": "ASM" },
        { "value": "BENCH_ASM", "label": "BENCH ASM" },
        { "value": "BENCH_SM", "label": "BENCH SM" },
        { "value": "CASHIER", "label": "CASHIER" },
        { "value": "CUSTOMER_RETURN", "label": "CUSTOMER RETURN" },
        { "value": "ELECTRICIAN", "label": "ELECTRICIAN" },
        { "value": "FM", "label": "FM" },
        { "value": "HK", "label": "HK" },
        { "value": "INTERNAL_SECURITY", "label": "INTERNAL SECURITY" },
        { "value": "LOBM", "label": "LOBM" },
        { "value": "LP", "label": "LP" },
        { "value": "NAPS_LOBM", "label": "NAPS LOBM" },
        { "value": "SECURITY_GUARD", "label": "SECURITY GUARD" },
        { "value": "SM", "label": "SM" },
        { "value": "TINNY_WINNY_LOBM", "label": "TINNY/WINNY-LOBM" }
    ],
    "SCM": [
        { "value": "ASST._DEPT._HEAD", "label": "ASST. DEPT. HEAD" },
        { "value": "ASST._MANAGER", "label": "ASST. MANAGER" },
        { "value": "ASST.DC_HEAD", "label": "ASST.DC HEAD" },
        { "value": "DC_HEAD", "label": "DC HEAD" },
        { "value": "DEPT_HEAD", "label": "DEPT HEAD" },
        { "value": "DEPT._HEAD", "label": "DEPT. HEAD" },
        { "value": "DIV_HEAD", "label": "DIV HEAD" },
        { "value": "DRIVER", "label": "DRIVER" },
        { "value": "DRIVER_HELPER", "label": "DRIVER HELPER" },
        { "value": "ELECTRICIAN", "label": "ELECTRICIAN" },
        { "value": "EXECUTIVE", "label": "EXECUTIVE" },
        { "value": "HEAD_SCM", "label": "HEAD SCM" },
        { "value": "HUB_INCHARGE", "label": "HUB INCHARGE" },
        { "value": "HUB_CORDINATOR", "label": "HUB-CORDINATOR" },
        { "value": "INTERNAL", "label": "INTERNAL" },
        { "value": "LADY_GUARD", "label": "LADY GUARD" },
        { "value": "LP", "label": "LP" },
        { "value": "LPO", "label": "LPO" },
        { "value": "MANAGEMENT_TRAINEE", "label": "MANAGEMENT TRAINEE" },
        { "value": "MANAGER", "label": "MANAGER" },
        { "value": "MT", "label": "MT" },
        { "value": "OPTR", "label": "OPTR" },
        { "value": "RLPO", "label": "RLPO" },
        { "value": "SENIOR_EXECUTIVE", "label": "SENIOR EXECUTIVE" },
        { "value": "SENIOR_LPO", "label": "SENIOR LPO" },
        { "value": "SUPERVISOR", "label": "SUPERVISOR" },
        { "value": "TL", "label": "TL" },
        { "value": "TRANSPORT_MANAGER", "label": "TRANSPORT MANAGER" }
    ],
};
