import os
import re

def clean_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original_content = content

    # Clean up redundant dark texts generated by consecutive regex replacements
    content = re.sub(r'dark:text-slate-[0-9]+\s+dark:text-white', 'dark:text-white', content)
    content = re.sub(r'dark:text-slate-[3-8]00\s+dark:text-slate-[3-8]00', lambda m: m.group(0).split()[0], content) # take the first one
    content = re.sub(r'dark:text-slate-800\s+dark:text-slate-200', 'dark:text-slate-200', content)
    content = re.sub(r'dark:text-slate-600\s+dark:text-slate-400', 'dark:text-slate-400', content)
    content = re.sub(r'dark:text-slate-400\s+dark:text-slate-500', 'dark:text-slate-400', content)
    
    # Hover duplicates
    content = re.sub(r'hover:text-slate-[0-9]+\s+dark:hover:bg-white/5\s+hover:bg-slate-100', 'hover:bg-slate-100 dark:hover:bg-white/5 hover:text-slate-900', content)
    content = re.sub(r'hover:text-slate-[0-9]+\s+dark:text-white\s+hover:text-slate-900', 'hover:text-slate-900 dark:hover:text-white', content)
    content = re.sub(r'hover:bg-slate-200\s+hover:text-slate-[0-9]+\s+dark:hover:bg-white/10\s+hover:bg-slate-200', 'hover:bg-slate-200 dark:hover:bg-white/10 hover:text-slate-900', content)
    
    if content != original_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Cleaned {filepath}")

def main():
    target_dirs = ['frontend/components', 'frontend/pages']
    for directory in target_dirs:
        for root, _, files in os.walk(directory):
            for file in files:
                if file.endswith('.jsx'):
                    clean_file(os.path.join(root, file))

if __name__ == "__main__":
    main()
