"""add_multitenant_hierarchy

Revision ID: 311b2c48e7fd
Revises: bed804741718
Create Date: 2026-04-13 00:25:15.591482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '311b2c48e7fd'
down_revision = 'bed804741718'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_requests', sa.Column('company_id', sa.UUID(), nullable=True), schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_company_id'), 'asset_requests', ['company_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_current_owner_role'), 'asset_requests', ['current_owner_role'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_procurement_stage'), 'asset_requests', ['procurement_stage'], unique=False, schema='asset')
    op.create_foreign_key(None, 'asset_requests', 'companies', ['company_id'], ['id'], source_schema='asset', referent_schema='public', ondelete='CASCADE')
    op.add_column('assets', sa.Column('company_id', sa.UUID(), nullable=True), schema='asset')
    op.drop_index('idx_asset_created_status', table_name='assets', schema='asset')
    op.drop_index('idx_asset_status_segment', table_name='assets', schema='asset')
    op.drop_index('idx_asset_type_status', table_name='assets', schema='asset')
    op.drop_index('ix_asset_created_at', table_name='assets', schema='asset')
    op.create_index(op.f('ix_asset_assets_company_id'), 'assets', ['company_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_created_at'), 'assets', ['created_at'], unique=False, schema='asset')
    op.drop_constraint('assets_location_id_fkey', 'assets', schema='asset', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'companies', ['company_id'], ['id'], source_schema='asset', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'assets', 'locations', ['location_id'], ['id'], source_schema='asset', referent_schema='asset', ondelete='SET NULL')
    op.alter_column('patch_compliance_snapshots', 'snapshot_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='asset')
    op.alter_column('patch_deployment_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='asset')
    op.drop_index('ix_patch_deployment_jobs_status', table_name='patch_deployment_jobs', schema='asset')
    op.create_index(op.f('ix_asset_patch_deployment_jobs_id'), 'patch_deployment_jobs', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_patch_deployment_jobs_patch_id'), 'patch_deployment_jobs', ['patch_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_patch_deployment_jobs_status'), 'patch_deployment_jobs', ['status'], unique=False, schema='asset')
    op.alter_column('patch_deployments', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='asset')
    op.alter_column('patch_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='asset')
    op.drop_index('ix_patch_logs_asset_id', table_name='patch_logs', schema='asset')
    op.drop_index('ix_patch_logs_deployment_id', table_name='patch_logs', schema='asset')
    op.create_index(op.f('ix_asset_patch_logs_asset_id'), 'patch_logs', ['asset_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_patch_logs_deployment_id'), 'patch_logs', ['deployment_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_patch_logs_id'), 'patch_logs', ['id'], unique=False, schema='asset')
    op.alter_column('system_patches', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='asset')
    op.create_index(op.f('ix_asset_system_patches_kb_article_id'), 'system_patches', ['kb_article_id'], unique=False, schema='asset')
    op.drop_column('system_patches', 'is_custom', schema='asset')
    op.drop_column('system_patches', 'binary_url', schema='asset')
    op.add_column('departments', sa.Column('company_id', sa.UUID(), nullable=True), schema='auth')
    op.add_column('departments', sa.Column('parent_id', sa.UUID(), nullable=True), schema='auth')
    op.create_index(op.f('ix_auth_departments_company_id'), 'departments', ['company_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_departments_parent_id'), 'departments', ['parent_id'], unique=False, schema='auth')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='SET NULL')
    op.create_foreign_key(None, 'departments', 'companies', ['company_id'], ['id'], source_schema='auth', referent_schema='public', ondelete='CASCADE')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True), schema='auth')
    op.create_index(op.f('ix_auth_users_company_id'), 'users', ['company_id'], unique=False, schema='auth')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], source_schema='auth', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('purchase_invoices_purchase_order_id_fkey', 'purchase_invoices', schema='procurement', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_invoices', 'purchase_orders', ['purchase_order_id'], ['id'], source_schema='procurement', referent_schema='procurement', ondelete='CASCADE')
    op.drop_index('idx_po_status_recv', table_name='purchase_orders', schema='procurement', postgresql_where="((status)::text = 'RECEIVED'::text)")
    op.drop_index('ix_purchase_orders_created_at', table_name='purchase_orders', schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False, schema='procurement')
    op.drop_constraint('assignment_group_members_group_id_user_id_key', 'assignment_group_members', schema='support', type_='unique')
    op.create_index('ix_group_member_unique', 'assignment_group_members', ['group_id', 'user_id'], unique=True, schema='support')
    op.create_index(op.f('ix_support_assignment_group_members_id'), 'assignment_group_members', ['id'], unique=False, schema='support')
    op.drop_constraint('assignment_groups_name_key', 'assignment_groups', schema='support', type_='unique')
    op.create_index(op.f('ix_support_assignment_groups_id'), 'assignment_groups', ['id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_assignment_groups_name'), 'assignment_groups', ['name'], unique=True, schema='support')
    op.drop_constraint('assignment_groups_manager_id_fkey', 'assignment_groups', schema='support', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_groups', 'users', ['manager_id'], ['id'], source_schema='support', referent_schema='auth', ondelete='SET NULL')
    op.create_index(op.f('ix_support_tasks_id'), 'tasks', ['id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_tasks_status'), 'tasks', ['status'], unique=False, schema='support')
    op.create_index(op.f('ix_support_tasks_ticket_id'), 'tasks', ['ticket_id'], unique=False, schema='support')
    op.alter_column('ticket_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='support')
    op.create_index(op.f('ix_support_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False, schema='support')
    op.alter_column('ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='support')
    op.create_index(op.f('ix_support_ticket_comments_id'), 'ticket_comments', ['id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False, schema='support')
    op.add_column('tickets', sa.Column('company_id', sa.UUID(), nullable=True), schema='support')
    op.drop_index('idx_tickets_status_created', table_name='tickets', schema='support')
    op.drop_index('ix_tickets_assignment_group_id', table_name='tickets', schema='support')
    op.drop_index('ix_tickets_created_at', table_name='tickets', schema='support')
    op.drop_index('ix_tickets_display_id', table_name='tickets', schema='support')
    op.drop_constraint('tickets_display_id_key', 'tickets', schema='support', type_='unique')
    op.create_index(op.f('ix_support_tickets_company_id'), 'tickets', ['company_id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_tickets_created_at'), 'tickets', ['created_at'], unique=False, schema='support')
    op.create_index(op.f('ix_support_tickets_display_id'), 'tickets', ['display_id'], unique=True, schema='support')
    op.drop_constraint('tickets_target_department_id_fkey', 'tickets', schema='support', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'departments', ['target_department_id'], ['id'], source_schema='support', referent_schema='auth', ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'], source_schema='support', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_public_agent_configurations_agent_id', table_name='agent_configurations', schema='system')
    op.create_index(op.f('ix_system_agent_configurations_agent_id'), 'agent_configurations', ['agent_id'], unique=False, schema='system')
    op.drop_index('ix_notifications_source', table_name='notifications', schema='system')
    op.create_index(op.f('ix_system_notifications_created_at'), 'notifications', ['created_at'], unique=False, schema='system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_notifications_created_at'), table_name='notifications', schema='system')
    op.create_index('ix_notifications_source', 'notifications', ['source'], unique=False, schema='system')
    op.drop_index(op.f('ix_system_agent_configurations_agent_id'), table_name='agent_configurations', schema='system')
    op.create_index('ix_public_agent_configurations_agent_id', 'agent_configurations', ['agent_id'], unique=False, schema='system')
    op.drop_constraint(None, 'tickets', schema='support', type_='foreignkey')
    op.drop_constraint(None, 'tickets', schema='support', type_='foreignkey')
    op.create_foreign_key('tickets_target_department_id_fkey', 'tickets', 'departments', ['target_department_id'], ['id'], source_schema='support', referent_schema='auth')
    op.drop_index(op.f('ix_support_tickets_display_id'), table_name='tickets', schema='support')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='tickets', schema='support')
    op.drop_index(op.f('ix_support_tickets_company_id'), table_name='tickets', schema='support')
    op.create_unique_constraint('tickets_display_id_key', 'tickets', ['display_id'], schema='support')
    op.create_index('ix_tickets_display_id', 'tickets', ['display_id'], unique=False, schema='support')
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'], unique=False, schema='support')
    op.create_index('ix_tickets_assignment_group_id', 'tickets', ['assignment_group_id'], unique=False, schema='support')
    op.create_index('idx_tickets_status_created', 'tickets', ['status', sa.text('created_at DESC')], unique=False, schema='support')
    op.drop_column('tickets', 'company_id', schema='support')
    op.drop_index(op.f('ix_support_ticket_comments_ticket_id'), table_name='ticket_comments', schema='support')
    op.drop_index(op.f('ix_support_ticket_comments_id'), table_name='ticket_comments', schema='support')
    op.alter_column('ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='support')
    op.drop_index(op.f('ix_support_ticket_attachments_ticket_id'), table_name='ticket_attachments', schema='support')
    op.drop_index(op.f('ix_support_ticket_attachments_id'), table_name='ticket_attachments', schema='support')
    op.alter_column('ticket_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='support')
    op.drop_index(op.f('ix_support_tasks_ticket_id'), table_name='tasks', schema='support')
    op.drop_index(op.f('ix_support_tasks_status'), table_name='tasks', schema='support')
    op.drop_index(op.f('ix_support_tasks_id'), table_name='tasks', schema='support')
    op.drop_constraint(None, 'assignment_groups', schema='support', type_='foreignkey')
    op.create_foreign_key('assignment_groups_manager_id_fkey', 'assignment_groups', 'users', ['manager_id'], ['id'], source_schema='support', referent_schema='auth')
    op.drop_index(op.f('ix_support_assignment_groups_name'), table_name='assignment_groups', schema='support')
    op.drop_index(op.f('ix_support_assignment_groups_id'), table_name='assignment_groups', schema='support')
    op.create_unique_constraint('assignment_groups_name_key', 'assignment_groups', ['name'], schema='support')
    op.drop_index(op.f('ix_support_assignment_group_members_id'), table_name='assignment_group_members', schema='support')
    op.drop_index('ix_group_member_unique', table_name='assignment_group_members', schema='support')
    op.create_unique_constraint('assignment_group_members_group_id_user_id_key', 'assignment_group_members', ['group_id', 'user_id'], schema='support')
    op.drop_index(op.f('ix_procurement_purchase_orders_created_at'), table_name='purchase_orders', schema='procurement')
    op.create_index('ix_purchase_orders_created_at', 'purchase_orders', ['created_at'], unique=False, schema='procurement')
    op.create_index('idx_po_status_recv', 'purchase_orders', ['status'], unique=False, schema='procurement', postgresql_where="((status)::text = 'RECEIVED'::text)")
    op.drop_constraint(None, 'purchase_invoices', schema='procurement', type_='foreignkey')
    op.create_foreign_key('purchase_invoices_purchase_order_id_fkey', 'purchase_invoices', 'purchase_orders', ['purchase_order_id'], ['id'], source_schema='procurement', referent_schema='procurement')
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_index(op.f('ix_auth_users_company_id'), table_name='users', schema='auth')
    op.drop_column('users', 'company_id', schema='auth')
    op.drop_constraint(None, 'departments', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'departments', schema='auth', type_='foreignkey')
    op.drop_index(op.f('ix_auth_departments_parent_id'), table_name='departments', schema='auth')
    op.drop_index(op.f('ix_auth_departments_company_id'), table_name='departments', schema='auth')
    op.drop_column('departments', 'parent_id', schema='auth')
    op.drop_column('departments', 'company_id', schema='auth')
    op.add_column('system_patches', sa.Column('binary_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True), schema='asset')
    op.add_column('system_patches', sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False), schema='asset')
    op.drop_index(op.f('ix_asset_system_patches_kb_article_id'), table_name='system_patches', schema='asset')
    op.alter_column('system_patches', 'release_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='asset')
    op.drop_index(op.f('ix_asset_patch_logs_id'), table_name='patch_logs', schema='asset')
    op.drop_index(op.f('ix_asset_patch_logs_deployment_id'), table_name='patch_logs', schema='asset')
    op.drop_index(op.f('ix_asset_patch_logs_asset_id'), table_name='patch_logs', schema='asset')
    op.create_index('ix_patch_logs_deployment_id', 'patch_logs', ['deployment_id'], unique=False, schema='asset')
    op.create_index('ix_patch_logs_asset_id', 'patch_logs', ['asset_id'], unique=False, schema='asset')
    op.alter_column('patch_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='asset')
    op.alter_column('patch_deployments', 'installed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='asset')
    op.drop_index(op.f('ix_asset_patch_deployment_jobs_status'), table_name='patch_deployment_jobs', schema='asset')
    op.drop_index(op.f('ix_asset_patch_deployment_jobs_patch_id'), table_name='patch_deployment_jobs', schema='asset')
    op.drop_index(op.f('ix_asset_patch_deployment_jobs_id'), table_name='patch_deployment_jobs', schema='asset')
    op.create_index('ix_patch_deployment_jobs_status', 'patch_deployment_jobs', ['status'], unique=False, schema='asset')
    op.alter_column('patch_deployment_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='asset')
    op.alter_column('patch_compliance_snapshots', 'snapshot_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='asset')
    op.drop_constraint(None, 'assets', schema='asset', type_='foreignkey')
    op.drop_constraint(None, 'assets', schema='asset', type_='foreignkey')
    op.create_foreign_key('assets_location_id_fkey', 'assets', 'locations', ['location_id'], ['id'], source_schema='asset', referent_schema='asset')
    op.drop_index(op.f('ix_asset_assets_created_at'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_company_id'), table_name='assets', schema='asset')
    op.create_index('ix_asset_created_at', 'assets', ['created_at'], unique=False, schema='asset')
    op.create_index('idx_asset_type_status', 'assets', ['type', 'status'], unique=False, schema='asset')
    op.create_index('idx_asset_status_segment', 'assets', ['status', 'segment'], unique=False, schema='asset')
    op.create_index('idx_asset_created_status', 'assets', [sa.text('created_at DESC'), 'status'], unique=False, schema='asset')
    op.drop_column('assets', 'company_id', schema='asset')
    op.drop_constraint(None, 'asset_requests', schema='asset', type_='foreignkey')
    op.drop_index(op.f('ix_asset_asset_requests_procurement_stage'), table_name='asset_requests', schema='asset')
    op.drop_index(op.f('ix_asset_asset_requests_current_owner_role'), table_name='asset_requests', schema='asset')
    op.drop_index(op.f('ix_asset_asset_requests_company_id'), table_name='asset_requests', schema='asset')
    op.drop_column('asset_requests', 'company_id', schema='asset')
    # ### end Alembic commands ###
