"""add_automation_models

Revision ID: 4b27366ffeaf
Revises: add_patch_root_enhancements
Create Date: 2026-03-15 17:11:45.950559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b27366ffeaf'
down_revision = 'add_patch_root_enhancements'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('current_stage_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_change_approvals_id'), 'change_approvals', ['id'], unique=False, schema='support')
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('response_time_limit', sa.Integer(), nullable=True),
    sa.Column('resolution_time_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_sla_policies_id'), 'sla_policies', ['id'], unique=False, schema='support')
    op.create_table('workflow_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_workflow_rules_id'), 'workflow_rules', ['id'], unique=False, schema='support')
    op.create_table('ticket_slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sla_policy_id', sa.UUID(), nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['support.sla_policies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_ticket_slas_id'), 'ticket_slas', ['id'], unique=False, schema='support')
    op.create_foreign_key(None, 'asset_assignments', 'users', ['user_id'], ['id'], source_schema='asset', referent_schema='auth')
    op.create_foreign_key(None, 'asset_requests', 'users', ['requester_id'], ['id'], source_schema='asset', referent_schema='auth')
    op.drop_column('assets', 'is_pilot', schema='asset')
    op.drop_index('ix_gate_passes_asset_id', table_name='gate_passes', schema='asset')
    op.drop_index('ix_gate_passes_status', table_name='gate_passes', schema='asset')
    op.create_index(op.f('ix_asset_gate_passes_asset_id'), 'gate_passes', ['asset_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_gate_passes_id'), 'gate_passes', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_gate_passes_status'), 'gate_passes', ['status'], unique=False, schema='asset')
    op.drop_index('ix_asset_patch_snapshots_asset_id', table_name='patch_compliance_snapshots', schema='asset')
    op.drop_index('ix_asset_patch_snapshots_snapshot_date', table_name='patch_compliance_snapshots', schema='asset')
    op.create_index(op.f('ix_asset_patch_compliance_snapshots_asset_id'), 'patch_compliance_snapshots', ['asset_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_patch_compliance_snapshots_snapshot_date'), 'patch_compliance_snapshots', ['snapshot_date'], unique=False, schema='asset')
    op.drop_constraint('patch_compliance_snapshots_asset_id_fkey', 'patch_compliance_snapshots', schema='asset', type_='foreignkey')
    op.create_foreign_key(None, 'patch_compliance_snapshots', 'assets', ['asset_id'], ['id'], source_schema='asset', referent_schema='asset')
    op.create_index(op.f('ix_asset_patch_schedules_id'), 'patch_schedules', ['id'], unique=False, schema='asset')
    op.drop_constraint('patch_schedules_patch_id_fkey', 'patch_schedules', schema='asset', type_='foreignkey')
    op.create_foreign_key(None, 'patch_schedules', 'system_patches', ['patch_id'], ['id'], source_schema='asset', referent_schema='asset')
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.drop_column('category_configs', 'target_department', schema='support')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_id'], ['id'], source_schema='support', referent_schema='auth')
    op.create_foreign_key(None, 'tickets', 'users', ['requestor_id'], ['id'], source_schema='support', referent_schema='auth')
    op.drop_column('tickets', 'target_department', schema='support')
    op.create_index(op.f('ix_system_agent_commands_id'), 'agent_commands', ['id'], unique=False, schema='system')
    op.drop_constraint('agent_commands_asset_id_fkey', 'agent_commands', schema='system', type_='foreignkey')
    op.create_foreign_key(None, 'agent_commands', 'assets', ['asset_id'], ['id'], source_schema='system', referent_schema='asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_commands', schema='system', type_='foreignkey')
    op.create_foreign_key('agent_commands_asset_id_fkey', 'agent_commands', 'assets', ['asset_id'], ['id'], source_schema='system', referent_schema='asset', ondelete='CASCADE')
    op.drop_index(op.f('ix_system_agent_commands_id'), table_name='agent_commands', schema='system')
    op.add_column('tickets', sa.Column('target_department', sa.VARCHAR(), server_default=sa.text("'IT'::character varying"), autoincrement=False, nullable=True), schema='support')
    op.drop_constraint(None, 'tickets', schema='support', type_='foreignkey')
    op.drop_constraint(None, 'tickets', schema='support', type_='foreignkey')
    op.add_column('category_configs', sa.Column('target_department', sa.VARCHAR(), server_default=sa.text("'IT'::character varying"), autoincrement=False, nullable=True), schema='support')
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'patch_schedules', schema='asset', type_='foreignkey')
    op.create_foreign_key('patch_schedules_patch_id_fkey', 'patch_schedules', 'system_patches', ['patch_id'], ['id'], source_schema='asset', referent_schema='asset', ondelete='CASCADE')
    op.drop_index(op.f('ix_asset_patch_schedules_id'), table_name='patch_schedules', schema='asset')
    op.drop_constraint(None, 'patch_compliance_snapshots', schema='asset', type_='foreignkey')
    op.create_foreign_key('patch_compliance_snapshots_asset_id_fkey', 'patch_compliance_snapshots', 'assets', ['asset_id'], ['id'], source_schema='asset', referent_schema='asset', ondelete='CASCADE')
    op.drop_index(op.f('ix_asset_patch_compliance_snapshots_snapshot_date'), table_name='patch_compliance_snapshots', schema='asset')
    op.drop_index(op.f('ix_asset_patch_compliance_snapshots_asset_id'), table_name='patch_compliance_snapshots', schema='asset')
    op.create_index('ix_asset_patch_snapshots_snapshot_date', 'patch_compliance_snapshots', ['snapshot_date'], unique=False, schema='asset')
    op.create_index('ix_asset_patch_snapshots_asset_id', 'patch_compliance_snapshots', ['asset_id'], unique=False, schema='asset')
    op.drop_index(op.f('ix_asset_gate_passes_status'), table_name='gate_passes', schema='asset')
    op.drop_index(op.f('ix_asset_gate_passes_id'), table_name='gate_passes', schema='asset')
    op.drop_index(op.f('ix_asset_gate_passes_asset_id'), table_name='gate_passes', schema='asset')
    op.create_index('ix_gate_passes_status', 'gate_passes', ['status'], unique=False, schema='asset')
    op.create_index('ix_gate_passes_asset_id', 'gate_passes', ['asset_id'], unique=False, schema='asset')
    op.add_column('assets', sa.Column('is_pilot', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False), schema='asset')
    op.drop_constraint(None, 'asset_requests', schema='asset', type_='foreignkey')
    op.drop_constraint(None, 'asset_assignments', schema='asset', type_='foreignkey')
    op.drop_index(op.f('ix_support_ticket_slas_id'), table_name='ticket_slas', schema='support')
    op.drop_table('ticket_slas', schema='support')
    op.drop_index(op.f('ix_support_workflow_rules_id'), table_name='workflow_rules', schema='support')
    op.drop_table('workflow_rules', schema='support')
    op.drop_index(op.f('ix_support_sla_policies_id'), table_name='sla_policies', schema='support')
    op.drop_table('sla_policies', schema='support')
    op.drop_index(op.f('ix_support_change_approvals_id'), table_name='change_approvals', schema='support')
    op.drop_table('change_approvals', schema='support')
    # ### end Alembic commands ###
