"""add_password_reset_tokens

Revision ID: 8ba0b01e1d59
Revises: f08f544761c2
Create Date: 2026-02-10 00:39:00.394406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba0b01e1d59'
down_revision = 'f08f544761c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_password_reset_tokens_user_id'), table_name='password_reset_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_password_reset_tokens_token'), table_name='password_reset_tokens', schema='auth')
    op.drop_table('password_reset_tokens', schema='auth')
    # ### end Alembic commands ###
