"""add specifications to asset_requests

Revision ID: d934940bcffb
Revises: add_finance_records
Create Date: 2026-02-22 04:12:20.585288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd934940bcffb'
down_revision = 'add_finance_records'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_discovery_diffs_asset', table_name='discovery_diffs', schema='system')
    op.drop_index('idx_discovery_diffs_detected_at', table_name='discovery_diffs', schema='system')
    op.drop_index('idx_discovery_diffs_scan', table_name='discovery_diffs', schema='system')
    op.drop_table('discovery_diffs', schema='system')
    op.add_column('asset_requests', sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='asset')
    op.drop_index('idx_discovery_scans_agent', table_name='discovery_scans', schema='system')
    op.drop_index('idx_discovery_scans_start_time', table_name='discovery_scans', schema='system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_discovery_scans_start_time', 'discovery_scans', [sa.text('start_time DESC')], unique=False, schema='system')
    op.create_index('idx_discovery_scans_agent', 'discovery_scans', ['agent_id'], unique=False, schema='system')
    op.drop_column('asset_requests', 'specifications', schema='asset')
    op.create_table('discovery_diffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.assets.id'], name='discovery_diffs_asset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['system.discovery_scans.id'], name='discovery_diffs_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='discovery_diffs_pkey'),
    schema='system'
    )
    op.create_index('idx_discovery_diffs_scan', 'discovery_diffs', ['scan_id'], unique=False, schema='system')
    op.create_index('idx_discovery_diffs_detected_at', 'discovery_diffs', [sa.text('detected_at DESC')], unique=False, schema='system')
    op.create_index('idx_discovery_diffs_asset', 'discovery_diffs', ['asset_id'], unique=False, schema='system')
    # ### end Alembic commands ###
