"""sync_models_final

Revision ID: f08f544761c2
Revises: add_agent_schedules
Create Date: 2026-02-10 00:35:00.689839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f08f544761c2'
down_revision = 'add_agent_schedules'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments', schema='support')
    op.drop_table('ticket_assets', schema='support')
    op.drop_table('manager_approvals', schema='asset')
    op.drop_table('ticket_comments', schema='support')
    op.drop_index('idx_maintenance_asset_id', table_name='maintenance', schema='asset')
    op.drop_table('maintenance', schema='asset')
    op.drop_index('idx_agent_configurations_agent_id', table_name='agent_configurations')
    op.drop_constraint('uq_agent_config', 'agent_configurations', type_='unique')
    op.create_index(op.f('ix_public_agent_configurations_agent_id'), 'agent_configurations', ['agent_id'], unique=False, schema='public')
    op.drop_constraint('asset_assignments_assigned_by_fkey', 'asset_assignments', schema='asset', type_='foreignkey')
    op.drop_constraint('asset_assignments_user_id_fkey', 'asset_assignments', schema='asset', type_='foreignkey')
    op.drop_constraint('byod_devices_user_id_fkey', 'byod_devices', schema='asset', type_='foreignkey')
    op.drop_constraint('byod_devices_asset_request_id_fkey', 'byod_devices', schema='asset', type_='foreignkey')
    op.drop_constraint('purchase_requests_asset_request_id_fkey', 'purchase_requests', schema='procurement', type_='foreignkey')
    op.drop_constraint('purchase_requests_requested_by_fkey', 'purchase_requests', schema='procurement', type_='foreignkey')
    op.drop_constraint('fk_asset_request_id', 'assets', schema='asset', type_='foreignkey')

    op.alter_column('asset_assignments', 'assigned_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True,
               schema='asset')
    op.alter_column('asset_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='asset')
    op.create_index(op.f('ix_asset_asset_assignments_asset_id'), 'asset_assignments', ['asset_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_assignments_id'), 'asset_assignments', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_assignments_user_id'), 'asset_assignments', ['user_id'], unique=False, schema='asset')
    op.drop_column('asset_assignments', 'returned_at', schema='asset')
    op.drop_column('asset_assignments', 'accepted', schema='asset')
    op.drop_constraint('asset_inventory_asset_id_key', 'asset_inventory', schema='asset', type_='unique')
    op.drop_index('ix_asset_asset_inventory_asset_id', table_name='asset_inventory', schema='asset')
    op.create_index(op.f('ix_asset_asset_inventory_asset_id'), 'asset_inventory', ['asset_id'], unique=True, schema='asset')
    op.alter_column('asset_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.alter_column('asset_relationships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.drop_index('idx_asset_relationships_metadata_gin', table_name='asset_relationships', schema='asset', postgresql_using='gin')
    op.drop_index('idx_asset_relationships_source', table_name='asset_relationships', schema='asset')
    op.drop_index('idx_asset_relationships_target', table_name='asset_relationships', schema='asset')
    op.drop_index('idx_asset_relationships_type', table_name='asset_relationships', schema='asset')
    op.create_index(op.f('ix_asset_asset_relationships_id'), 'asset_relationships', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_relationships_relationship_type'), 'asset_relationships', ['relationship_type'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False, schema='asset')
    op.alter_column('asset_requests', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Medium'::character varying"),
               schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_id'), 'asset_requests', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_requester_id'), 'asset_requests', ['requester_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_asset_requests_status'), 'asset_requests', ['status'], unique=False, schema='asset')
    op.drop_column('asset_requests', 'inventory_checked_at', schema='asset')
    op.drop_column('asset_requests', 'allocated_asset_id', schema='asset')
    op.drop_column('asset_requests', 'rejection_reason', schema='asset')
    op.drop_column('asset_requests', 'procurement_order_id', schema='asset')
    op.drop_column('asset_requests', 'inventory_checked_by', schema='asset')
    op.drop_column('asset_requests', 'asset_available', schema='asset')
    op.drop_column('asset_requests', 'it_review_status', schema='asset')
    op.alter_column('assets', 'segment',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='asset')
    op.alter_column('assets', 'specifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'qc_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'configuration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='asset')
    op.drop_constraint('assets_serial_number_key', 'assets', schema='asset', type_='unique')
    op.drop_index('idx_asset_request_id', table_name='assets', schema='asset')
    op.create_index(op.f('ix_asset_assets_contract_expiry'), 'assets', ['contract_expiry'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_id'), 'assets', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_license_expiry'), 'assets', ['license_expiry'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_name'), 'assets', ['name'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_serial_number'), 'assets', ['serial_number'], unique=True, schema='asset')
    op.create_index(op.f('ix_asset_assets_status'), 'assets', ['status'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_assets_warranty_expiry'), 'assets', ['warranty_expiry'], unique=False, schema='asset')
    op.create_index('ix_asset_specifications_gin', 'assets', ['specifications'], unique=False, schema='asset', postgresql_using='gin')
    op.alter_column('byod_devices', 'request_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='asset')
    op.alter_column('byod_devices', 'device_model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='asset')
    op.alter_column('byod_devices', 'os_version',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='asset')
    op.alter_column('byod_devices', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='asset')
    op.alter_column('byod_devices', 'compliance_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='asset')
    op.alter_column('byod_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.create_index(op.f('ix_asset_byod_devices_id'), 'byod_devices', ['id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_byod_devices_owner_id'), 'byod_devices', ['owner_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_byod_devices_request_id'), 'byod_devices', ['request_id'], unique=False, schema='asset')
    op.create_index(op.f('ix_asset_byod_devices_serial_number'), 'byod_devices', ['serial_number'], unique=False, schema='asset')
    op.drop_column('byod_devices', 'asset_request_id', schema='asset')
    op.drop_column('byod_devices', 'mdm_enrolled', schema='asset')
    op.drop_column('byod_devices', 'deregistered_at', schema='asset')
    op.drop_column('byod_devices', 'registered_at', schema='asset')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"),
               schema='auth')
    op.drop_index('ix_users_sso_id', table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_status'), 'users', ['status'], unique=False, schema='auth')
    op.alter_column('purchase_invoices', 'created_by',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='procurement',
               postgresql_using='created_by::uuid')
    op.create_index(op.f('ix_procurement_purchase_invoices_id'), 'purchase_invoices', ['id'], unique=False, schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_invoices_purchase_order_id'), 'purchase_invoices', ['purchase_order_id'], unique=False, schema='procurement')
    op.create_foreign_key(None, 'purchase_invoices', 'purchase_orders', ['purchase_order_id'], ['id'], source_schema='procurement', referent_schema='procurement')
    op.alter_column('purchase_orders', 'uploaded_by',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='procurement',
               postgresql_using='uploaded_by::uuid')
    op.create_index(op.f('ix_procurement_purchase_orders_asset_request_id'), 'purchase_orders', ['asset_request_id'], unique=False, schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_orders_id'), 'purchase_orders', ['id'], unique=False, schema='procurement')
    op.create_foreign_key(None, 'purchase_orders', 'asset_requests', ['asset_request_id'], ['id'], source_schema='procurement', referent_schema='asset')
    op.alter_column('purchase_requests', 'asset_request_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               schema='procurement',
               postgresql_using='asset_id::uuid')
    op.alter_column('purchase_requests', 'requester_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='procurement')
    op.alter_column('purchase_requests', 'cost_estimate',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='procurement')
    op.alter_column('purchase_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='procurement')
    op.alter_column('purchase_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_requests_asset_id'), 'purchase_requests', ['asset_id'], unique=False, schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_requests_asset_request_id'), 'purchase_requests', ['asset_request_id'], unique=False, schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_requests_id'), 'purchase_requests', ['id'], unique=False, schema='procurement')
    op.create_index(op.f('ix_procurement_purchase_requests_requester_id'), 'purchase_requests', ['requester_id'], unique=False, schema='procurement')
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='support')
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='support')
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True,
               schema='support')
    op.alter_column('tickets', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='support')
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='support')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='support')
    op.create_index(op.f('ix_support_tickets_id'), 'tickets', ['id'], unique=False, schema='support')
    op.create_index(op.f('ix_support_tickets_status'), 'tickets', ['status'], unique=False, schema='support')
    op.drop_column('tickets', 'created_by', schema='support')
    op.drop_column('tickets', 'assigned_to', schema='support')
    op.drop_column('tickets', 'sla_deadline', schema='support')
    op.drop_column('tickets', 'resolved_at', schema='support')
    op.drop_constraint('api_tokens_token_key', 'api_tokens', schema='system', type_='unique')
    op.drop_index('ix_system_api_tokens_token', table_name='api_tokens', schema='system')
    op.create_index(op.f('ix_system_api_tokens_token'), 'api_tokens', ['token'], unique=True, schema='system')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='system')
    op.create_index('ix_audit_logs_details_gin', 'audit_logs', ['details'], unique=False, schema='system', postgresql_using='gin')
    op.create_index(op.f('ix_system_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False, schema='system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_audit_logs_timestamp'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_performed_by'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_entity_type'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_entity_id'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_action'), table_name='audit_logs', schema='system')
    op.drop_index('ix_audit_logs_details_gin', table_name='audit_logs', schema='system', postgresql_using='gin')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='system')
    op.drop_index(op.f('ix_system_api_tokens_token'), table_name='api_tokens', schema='system')
    op.create_index('ix_system_api_tokens_token', 'api_tokens', ['token'], unique=False, schema='system')
    op.create_unique_constraint('api_tokens_token_key', 'api_tokens', ['token'], schema='system')
    op.add_column('tickets', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='support')
    op.add_column('tickets', sa.Column('sla_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='support')
    op.add_column('tickets', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True), schema='support')
    op.add_column('tickets', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True), schema='support')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='tickets', schema='support')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='tickets', schema='support')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='support')
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='support')
    op.alter_column('tickets', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='support')
    op.alter_column('tickets', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               schema='support')
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='support')
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='support')
    op.create_foreign_key('purchase_requests_requested_by_fkey', 'purchase_requests', 'users', ['requester_id'], ['id'], source_schema='procurement', referent_schema='auth')
    op.create_foreign_key('purchase_requests_asset_request_id_fkey', 'purchase_requests', 'asset_requests', ['asset_request_id'], ['id'], source_schema='procurement', referent_schema='asset')
    op.drop_index(op.f('ix_procurement_purchase_requests_requester_id'), table_name='purchase_requests', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_requests_id'), table_name='purchase_requests', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_requests_asset_request_id'), table_name='purchase_requests', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_requests_asset_id'), table_name='purchase_requests', schema='procurement')
    op.alter_column('purchase_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='procurement')
    op.alter_column('purchase_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='procurement')
    op.alter_column('purchase_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'cost_estimate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'requester_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               schema='procurement')
    op.alter_column('purchase_requests', 'asset_request_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='procurement')
    op.drop_constraint(None, 'purchase_orders', schema='procurement', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_purchase_orders_id'), table_name='purchase_orders', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_orders_asset_request_id'), table_name='purchase_orders', schema='procurement')
    op.alter_column('purchase_orders', 'uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='procurement')
    op.drop_constraint(None, 'purchase_invoices', schema='procurement', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_purchase_invoices_purchase_order_id'), table_name='purchase_invoices', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_invoices_id'), table_name='purchase_invoices', schema='procurement')
    op.alter_column('purchase_invoices', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='procurement')
    op.drop_index(op.f('ix_auth_users_status'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.create_index('ix_users_sso_id', 'users', ['sso_id'], unique=False, schema='auth')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"),
               schema='auth')
    op.add_column('byod_devices', sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True), schema='asset')
    op.add_column('byod_devices', sa.Column('deregistered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='asset')
    op.add_column('byod_devices', sa.Column('mdm_enrolled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True), schema='asset')
    op.add_column('byod_devices', sa.Column('asset_request_id', sa.UUID(), autoincrement=False, nullable=True), schema='asset')
    op.create_foreign_key('byod_devices_asset_request_id_fkey', 'byod_devices', 'asset_requests', ['asset_request_id'], ['id'], source_schema='asset', referent_schema='asset')
    op.create_foreign_key('byod_devices_user_id_fkey', 'byod_devices', 'users', ['owner_id'], ['id'], source_schema='asset', referent_schema='auth')
    op.drop_index(op.f('ix_asset_byod_devices_serial_number'), table_name='byod_devices', schema='asset')
    op.drop_index(op.f('ix_asset_byod_devices_request_id'), table_name='byod_devices', schema='asset')
    op.drop_index(op.f('ix_asset_byod_devices_owner_id'), table_name='byod_devices', schema='asset')
    op.drop_index(op.f('ix_asset_byod_devices_id'), table_name='byod_devices', schema='asset')
    op.alter_column('byod_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.alter_column('byod_devices', 'compliance_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='asset')
    op.alter_column('byod_devices', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='asset')
    op.alter_column('byod_devices', 'os_version',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='asset')
    op.alter_column('byod_devices', 'device_model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='asset')
    op.alter_column('byod_devices', 'request_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='asset')
    op.create_foreign_key('fk_asset_request_id', 'assets', 'asset_requests', ['request_id'], ['id'], source_schema='asset', referent_schema='asset', ondelete='SET NULL')
    op.drop_index('ix_asset_specifications_gin', table_name='assets', schema='asset', postgresql_using='gin')
    op.drop_index(op.f('ix_asset_assets_warranty_expiry'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_status'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_serial_number'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_name'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_license_expiry'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_id'), table_name='assets', schema='asset')
    op.drop_index(op.f('ix_asset_assets_contract_expiry'), table_name='assets', schema='asset')
    op.create_index('idx_asset_request_id', 'assets', ['request_id'], unique=False, schema='asset')
    op.create_unique_constraint('assets_serial_number_key', 'assets', ['serial_number'], schema='asset')
    op.alter_column('assets', 'accepted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'configuration_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'qc_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='asset')
    op.alter_column('assets', 'segment',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='asset')
    op.add_column('asset_requests', sa.Column('it_review_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('asset_available', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('inventory_checked_by', sa.UUID(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('procurement_order_id', sa.UUID(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('allocated_asset_id', sa.UUID(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_requests', sa.Column('inventory_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='asset')
    op.drop_index(op.f('ix_asset_asset_requests_status'), table_name='asset_requests', schema='asset')
    op.drop_index(op.f('ix_asset_asset_requests_requester_id'), table_name='asset_requests', schema='asset')
    op.drop_index(op.f('ix_asset_asset_requests_id'), table_name='asset_requests', schema='asset')
    op.alter_column('asset_requests', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"),
               schema='asset')
    op.drop_index(op.f('ix_asset_asset_relationships_target_asset_id'), table_name='asset_relationships', schema='asset')
    op.drop_index(op.f('ix_asset_asset_relationships_source_asset_id'), table_name='asset_relationships', schema='asset')
    op.drop_index(op.f('ix_asset_asset_relationships_relationship_type'), table_name='asset_relationships', schema='asset')
    op.drop_index(op.f('ix_asset_asset_relationships_id'), table_name='asset_relationships', schema='asset')
    op.create_index('idx_asset_relationships_type', 'asset_relationships', ['relationship_type'], unique=False, schema='asset')
    op.create_index('idx_asset_relationships_target', 'asset_relationships', ['target_asset_id'], unique=False, schema='asset')
    op.create_index('idx_asset_relationships_source', 'asset_relationships', ['source_asset_id'], unique=False, schema='asset')
    op.create_index('idx_asset_relationships_metadata_gin', 'asset_relationships', ['metadata_'], unique=False, schema='asset', postgresql_using='gin')
    op.alter_column('asset_relationships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.alter_column('asset_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='asset')
    op.drop_index(op.f('ix_asset_asset_inventory_asset_id'), table_name='asset_inventory', schema='asset')
    op.create_index('ix_asset_asset_inventory_asset_id', 'asset_inventory', ['asset_id'], unique=False, schema='asset')
    op.create_unique_constraint('asset_inventory_asset_id_key', 'asset_inventory', ['asset_id'], schema='asset')
    op.add_column('asset_assignments', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='asset')
    op.add_column('asset_assignments', sa.Column('returned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='asset')
    op.create_foreign_key('asset_assignments_user_id_fkey', 'asset_assignments', 'users', ['user_id'], ['id'], source_schema='asset', referent_schema='auth')
    op.create_foreign_key('asset_assignments_assigned_by_fkey', 'asset_assignments', 'users', ['assigned_by'], ['id'], source_schema='asset', referent_schema='auth')
    op.drop_index(op.f('ix_asset_asset_assignments_user_id'), table_name='asset_assignments', schema='asset')
    op.drop_index(op.f('ix_asset_asset_assignments_id'), table_name='asset_assignments', schema='asset')
    op.drop_index(op.f('ix_asset_asset_assignments_asset_id'), table_name='asset_assignments', schema='asset')
    op.alter_column('asset_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='asset')
    op.alter_column('asset_assignments', 'assigned_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True,
               schema='asset')
    op.drop_index(op.f('ix_public_agent_configurations_agent_id'), table_name='agent_configurations', schema='public')
    op.create_unique_constraint('uq_agent_config', 'agent_configurations', ['agent_id', 'config_key'])
    op.create_index('idx_agent_configurations_agent_id', 'agent_configurations', ['agent_id'], unique=False)
    op.create_table('maintenance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=50), server_default=sa.text("'Preventive'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='maintenance_pkey'),
    schema='asset'
    )
    op.create_index('idx_maintenance_asset_id', 'maintenance', ['asset_id'], unique=False, schema='asset')
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('commented_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support.tickets.id'], name='ticket_comments_ticket_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ticket_comments_pkey'),
    schema='support'
    )
    op.create_table('manager_approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_request_id'], ['asset.asset_requests.id'], name='manager_approvals_asset_request_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['auth.users.id'], name='manager_approvals_manager_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='manager_approvals_pkey'),
    schema='asset'
    )
    op.create_table('ticket_assets',
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('association_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support.tickets.id'], name='ticket_assets_ticket_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'asset_id', name='ticket_assets_pkey'),
    schema='support'
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey'),
    schema='support'
    )
    # ### end Alembic commands ###
